### ISSUE TITLE
Graphical design fine-tuning

### ISSUE THREAD

**Issue by rcavaliere** [ilvalle/w2panalytics#19] opened 2015-11-03 14:15 UTC
In the "GRAPHICS" view, the X icons for closing the opened boxes must be improved according to the proposed layout.

**Comment by alessiovaralta** [comment] 2015-11-04 16:18
Hi, I have completed the Issue and created the pull request. I have a question about the logout button,  I have not found in the pdf document one button for the log out. There is this possibility?

**Comment by rcavaliere** [comment] 2015-11-04 17:30
You are right, we didn't have this feature now! Let's discuss it with our designers...

**Comment by rcavaliere** [comment] 2015-11-09 16:28
I have checked the new version of the application, but it seams that this enhancement has not been uploaded. Can you please check?

**Comment by alessiovaralta** [comment] 2015-11-09 17:25
Hi, I have sent all file and bertolla have made the merge. If I
clone the project from https://github.com/tis-innovation-park/w2panalytics
in my local web2py and go to the application there are my changes. If I try
to see these changes on line there aren't but I don't know about this last
passage.

**Comment by bertolla** [comment] 2016-01-20 16:52
Hi, I'm rolling back up this issues since it does not seem to be resolved yet. I did merged the pull request, the same day it was made. I also checked differences between this repo and the fork and there were no appart from docu. 

Furthermore I did check the code on github and found the bootstrap specific class `glyphicon-remove` applied  to the specific element. `/static/js/bootstrap-multiselect.js` line 324
Is this the problem or am I missing out something?

**Comment by alessiovaralta** [comment] 2016-01-21 07:48
Hi, I go to https://github.com/tis-innovation-park/w2panalytics and I have downloaded the project in local(https://github.com/tis-innovation-park/w2panalytics.git) and i see that the project is up to date. There is my last change. The size of selects and the x button is different from  the online version.
The problem is that the project that is online is not synchronized with the project in git and I don't know about this part. 
If you want to control the project in git for see that there are differences:
-Git clone in local and upload on you web2py in local
-Login in the application
-And in the first page when you select a station you can see my change(the x button and the different dimension of select)
So is not the github repository the problem but the online version.

**Comment by bertolla** [comment] 2016-01-21 08:07
Thank you for the fast response, I finally found the problem.
For some reason the application was deployed on 2 separate locations on the same server.
It seems like I pulled in the wrong one and therefore couldn't see any changes. The routing is done by the web2py framework and isn't very transparent.
Thank you for your time.

**Closed as completed** 2016-01-27 13:50 UTC
